FROM elixir:1.20.2-otp-28

RUN apt-get update -y && \
    apt-get install -y build-essential git && \
    apt-get clean && \
    rm -f /var/lib/apt/lists/*_*

WORKDIR /app

RUN mix local.hex --force && \
    mix local.rebar --force

ENV MIX_ENV=dev
ENV MIX_BUILD_DEPS=true
ENV MIX_QUIET=true

COPY mix.exs ./
RUN mix deps.get --only $MIX_ENV

COPY config config
RUN mix deps.compile

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

EXPOSE 4000

CMD ["/usr/local/bin/docker-entrypoint.sh"]
